config/routes.rb
Juvia::Application.routes.draw do
  match 'api/:action(.:format)', :to => 'api'
  root :to => 'admin/dashboard#index'
  
  devise_for :users
  
  namespace :admin do
    resources :comments do
      collection do
        get :preview
        get :import, :to => 'comments#new_import'
        post :import, :to => 'comments#import'
      end
      member do
        put :approve
      end
    end
    resources :sites do
      member do
        get :created
        get :test
      end
    end
    resources :users
    resources :topics
  end
  
  get 'admin/dashboard', :to => 'admin/dashboard#index', :as => :dashboard
  get 'admin/dashboard/new_admin', :to => 'admin/dashboard#new_admin'
  put 'admin/dashboard/create_admin', :to => 'admin/dashboard#create_admin'
  get 'admin/dashboard/new_site', :to => 'admin/dashboard#new_site'
  put 'admin/dashboard/create_site', :to => 'admin/dashboard#create_site'
  get 'admin/help(/:action)', :to => 'admin/help'
  
  match 'test/:action', :to => 'test' if Rails.env.test?

end

app/models/comment.rb
require 'digest/md5'
require 'net/http'
require 'cgi'

class Comment < ActiveRecord::Base
  class AkismetError < StandardError
  end

  belongs_to :topic, :inverse_of => :comments
  
  acts_as_enum :moderation_status, [:ok, :unchecked, :spam]
  
  scope :visible, where(:moderation_status => moderation_status(:ok))
  scope :requiring_moderation, where("moderation_status != #{moderation_status(:ok)}")
  
  validates_presence_of :content
  validates_presence_of :author_ip
  
  before_validation :nullify_blank_fields
  before_create :set_moderation_status
  after_create :update_topic_timestamp
  after_create :notify_moderators
  
  def site
    topic.site
  end

  def author_email=(value)
    value = value.to_s.strip
    write_attribute(:author_email, value.empty? ? nil : value)
  end

  def author_email_md5
    if author_email
      Digest::MD5.hexdigest(author_email.downcase)
    else
      nil
    end
  end
  
  def spam?
    response = call_akismet('comment-check', akismet_params)
    if response.body == 'invalid'
      if response['X-akismet-debug-help']
        message = "Akismet server error: " << response['X-akismet-debug-help']
      else
        message = "Unknown Akismet server error, maybe your API key is wrong"
      end
      raise AkismetError, message
    elsif response.body == 'true'
      true
    elsif response.body == 'false'
      false
    else
      raise AkismetError, "Akismet server error: #{response.body}"
    end
  end
  
  def report_ham
    call_akismet('submit-ham', akismet_params)
  end
  
  def report_spam
    call_akismet('submit-spam', akismet_params)
  end

private
  AKISMET_HEADERS = {
    'User-Agent' => "Juvia | Rails/#{Rails.version}",
    'Content-Type' => 'application/x-www-form-urlencoded'
  }
  
  def nullify_blank_fields
    self.author_name  = nil if author_name.blank?
    self.author_email = nil if author_email.blank?
    self.author_user_agent = nil if author_user_agent.blank?
    self.referer = nil if referer.blank?
  end
  
  def akismet_params
    raise AkismetError, "Site URL required for Akismet check" if topic.site.url.blank?
    params = {
      :blog => topic.site.url,
      :user_ip => author_ip,
      :user_agent => author_user_agent,
      :referrer => referer,
      :comment_content => content,
      :comment_type => 'comment'
    }
    params[:comment_author] = author_name if author_name.present?
    params[:comment_author_email] = author_email if author_email.present?
    params
  end
  
  def call_akismet(function_name, params)
    raise AkismetError, "Akismet key required" if topic.site.akismet_key.blank?
    uri = URI.parse("http://#{topic.site.akismet_key}.rest.akismet.com/1.1/#{function_name}")
    post_data = params.map { |k, v| "#{k}=#{CGI.escape(v.to_s)}" }.join('&')
    response = Net::HTTP.start(uri.host, uri.port) do |http|
      http.post(uri.path, post_data, AKISMET_HEADERS)
    end
    if response.code != "200"
      raise AkismetError, "Akismet internal error #{response.code}"
    else
      response
    end
  end
  
  def set_moderation_status
    case topic.site.moderation_method
    when :akismet
      self.moderation_status = spam? ? :spam : :ok
    when :manual
      self.moderation_status = :unchecked
    else
      self.moderation_status = :ok
    end
  end

  def update_topic_timestamp
    if topic
      topic.update_attribute(:last_posted_at, Time.now)
    end
  end

  def notify_moderators
    Mailer.comment_posted(self).deliver
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout 'admin'

  skip_authorization_check :only => [:preview, :new_import, :import]
  before_filter :set_navigation_ids
  before_filter :save_return_to_url, :only => [:new, :edit, :approve, :destroy]
  before_filter :require_admin!, :only => [:new_import, :import]

  def index
    authorize! :read, Comment
    @all_comments = Comment.
      accessible_by(current_ability).
      order('created_at DESC').
      includes(:topic)
    @comments = @all_comments.page(params[:page])
  end

  def edit
    @comment = Comment.find(params[:id])
    authorize! :update, @comment
  end

  def update
    @comment = Comment.find(params[:id])
    authorize! :update, @comment
    if @comment.update_attributes(params[:comment], :as => current_user.role)
      redirect_back(admin_comments_path)
    else
      render :action => 'edit'
    end
  end

  def preview
    render :text => ApplicationHelper.render_markdown(params[:content])
  end

  def approve
    @comment = Comment.find(params[:id])
    authorize! :update, @comment
    @comment.transaction do
      @comment.moderation_status = :ok
      if @comment.site.moderation_method == :akismet
        @comment.report_ham
      end
      @comment.save!
    end
    redirect_back(admin_comments_path)
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    @comment.transaction do
      if params[:spam] && @comment.site.moderation_method == :akismet
        @comment.report_spam
      end
      @comment.destroy
    end
    redirect_back(admin_comments_path)
  end

  def new_import
    @sites = Site.all
    @migrators = Juvia::Migrators::PLATFORMS.map{ |p| p.titleize }
  end

  def import
    options = {:table_prefix => params[:table_prefix],
      :wp_multisite_id => params[:wp_multisite_id]}
    if Juvia::Migrators.process(
      params[:site_id],
      params[:import_type],
      params[:database_name],
      params[:database_user],
      params[:database_password],
      params[:database_host],
      options
    )
      flash[:notice] = "Imported!"
      redirect_to(admin_comments_path)
    end
  end

private
  def set_navigation_ids
    @navigation_ids = [:dashboard, :comments]
  end
end

app/helpers/admin/comments_helper.rb
module Admin

module CommentsHelper
end

end # module Admin

app/views/admin/comments/_comment.html.erb
<%= div_for(comment, 'data-comment-id' => comment.id, :class => "moderation_status_#{comment.moderation_status}") do %>
  <div class="arrow"></div>
  <div class="shell">
    <div class="metadata">
      <div class="avatar">
  		  <img src="//www.gravatar.com/avatar/<%= comment.author_email_md5 %>?s=64"
  		  width="64"
  		  height="64"
  		  alt="<%= comment.author_name || 'Anonymous' %>">
  	  </div>
  	  <div class="author">
  	    <span class="name"><%= comment.author_name || 'Anonymous' %></span>
  	    <% if comment.author_email %>
  	      <span class="email">(<a href="mailto:<%= comment.author_email %>"><%= comment.author_email %></a>)</span>
  	    <% end %>
  	  </div>
  	  <div class="creation-time">
  	    wrote on <span class="value"><%= comment.created_at.strftime("%B %d %Y, %H:%M") %></span>
  	  </div>
      <% if local_assigns[:show_topic] %>
        <div class="associated-topic">
          (<%= link_to comment.site.name, [:admin, comment.site] %> /
           <%= link_to comment.topic.title, [:admin, comment.topic] %>)
        </div>
      <% end %>
  	</div>
    <div class="content">
      <%= render_markdown(comment.content) %>
    </div>
    <div class="actions button-container">
      <% if comment.moderation_status != :ok %>
        <% if comment.moderation_status == :unchecked %>
          <p><em>This comment is unchecked.</em></p>
        <% elsif comment.moderation_status == :spam %>
          <p><em>This appears to be spam.</em></p>
        <% else %>
          <% raise "Unknown moderation status #{comment.moderation_status.inspect}" %>
        <% end %>
        <%= positive_primary_approve_button_link_to 'Approve', approve_admin_comment_path(comment), :method => :put %>
      <% end %>
      <%= edit_button_link_to 'Edit', edit_admin_comment_path(comment, :return_to => request.fullpath) %>
      <%= button_group do %>
        <%= remove_button_link_to 'Mark as spam & delete', admin_comment_path(comment, :spam => true),
          :method => :delete,
          :confirm => 'Are you sure?',
          :return_to => request.fullpath %>
        <%= remove_button_link_to 'Delete', [:admin, comment],
          :method => :delete,
          :confirm => 'Are you sure?',
          :return_to => request.fullpath %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/comments/edit.html.erb
<h1>Editing comment by <%= @comment.author_name || 'Anonymous' %></h1>

<%= form_for([:admin, @comment], :html => { :class => 'comment' }) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="para">
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </div>

  <div class="para">
    <%= f.label :author_email %><br />
    <%= f.text_field :author_email %>
  </div>
  
  <div class="para">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="para actions">
    <%= f.submit :class => 'primary button' %>
    <%= button_link_to 'Cancel', session[:return_to] || admin_comments_path %>
  </div>
  
  <div class="para preview">
    <h3>Preview</h3>
    <div class="content">
      <%= render_markdown(@comment.content) %>
    </div>
  </div>
<% end %>

app/views/admin/comments/index.html.erb
<% @title = "Comments" %>
<div class="comments list">
  <% if @all_comments.empty? %>
    No comments have been posted.
  <% else %>
    <%= render :partial => 'admin/comments/comment',
      :collection => @comments,
      :locals => { :show_topic => true } %>
    <%= will_paginate @comments %>
  <% end %>
</div>

app/views/admin/comments/new_import.html.erb
<% @title = "Import Comments" %>
<%= form_tag(:import_admin_comments) do |f| %>

  <div class="para">
    <%= label_tag :site_id %><br />
    <%= select_tag :site_id, options_from_collection_for_select(@sites, 'id', 'name', params[:site_id].to_i) %>
  </div>

  <div class="para">
    <%= label_tag :import_type %><br />
    <%= select_tag :import_type, options_for_select(@migrators) %>
  </div>

  <div class="para">
    <%= label_tag :database_host %><br />
    <%= text_field_tag :database_host, 'localhost' %>
  </div>

  <div class="para">
    <%= label_tag :database_name %><br />
    <%= text_field_tag :database_name %>
  </div>

  <div class="para">
    <%= label_tag :database_user %><br />
    <%= text_field_tag :database_user %>
  </div>

  <div class="para">
    <%= label_tag :database_password %><br />
    <%= text_field_tag :database_password %>
  </div>

  <div class="para">
    <%= label_tag :table_prefix %> &mdash; The Wordpress table prefix (usually 'wp_')<br />
    <%= text_field_tag :table_prefix, 'wp_' %>
  </div>

  <div class="para">
    <%= label_tag :wp_multisite_id %> &mdash; The Wordpress Multisite site ID<br />
    Leave this field empty if importing from a non-multisite install, or from the base site of a multisite install.<br />
    <%= text_field_tag :wp_multisite_id %>
  </div>

  <div class="para actions">
    <%= primary_button_submit_tag('Import') %>
    <%= button_link_to 'Cancel', admin_comments_path %>
  </div>
<% end %>